// import { useState } from 'react';
// import Navbar from "../components/Navbar";
// import PVFooter from "../components/PVFooter";
// import { Button } from '../components/ui';

// const Home = () => {
//   const [searchText, setSearchText] = useState('');
//   const [searchTimeout, setSearchTimeout] = useState(null);
//   const [searchedResults, setSearchedResults] = useState([]);
//   const [isLoading, setIsLoading] = useState(false);

//   const handleSearchChange = (e) => {
//     clearTimeout(searchTimeout);
//     setSearchText(e.target.value);

//     setSearchTimeout(
//       setTimeout(() => {
//         // Here you would implement the actual search functionality
//         // For now, we'll just set a placeholder
//         setSearchedResults([]);
//       }, 500)
//     );
//   };

//   return (
//     <div className="min-h-screen bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 transition-colors duration-200">
//       <Navbar />

//       {/* Main Content */}
//       <main className="container mx-auto px-4 pt-24 pb-16">
//         {/* Header Section */}
//         <div className="text-center mb-12 mt-8">
//           <h1 className="font-extrabold text-5xl md:text-6xl bg-clip-text text-transparent bg-gradient-to-r from-[#6469ff] to-[#ff6b6b] mb-4">
//             The Community Showcase
//           </h1>
//           <p className="mt-4 text-gray-600 dark:text-gray-300 text-lg max-w-2xl mx-auto">
//             Browse through a collection of imaginative and visually stunning
//             images generated by AI.
//           </p>
//         </div>

//         {/* Search & Filter Section */}
//         <div className="max-w-4xl mx-auto mb-12">
//           <div className="flex flex-col md:flex-row gap-4">
//             <div className="relative flex-grow">
//               <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-5 h-5" />
//               <input
//                 type="text"
//                 placeholder="Search for images..."
//                 value={searchText}
//                 onChange={handleSearchChange}
//                 className="w-full pl-10 pr-4 py-3 rounded-xl border border-gray-200 dark:border-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-200 dark:focus:ring-blue-800 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 transition-all"
//               />
//             </div>
//             <button className="flex items-center justify-center gap-2 px-6 py-3 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors">
//               <Filter className="w-5 h-5 text-gray-600 dark:text-gray-300" />
//               <span className="text-gray-700 dark:text-gray-300">Filters</span>
//             </button>
//           </div>
//         </div>

//         {/* Gallery Section */}
//         <div className="mb-12">
//           <div className="flex justify-between items-center mb-6">
//             <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-200">Recent Creations</h2>
//             <button className="text-[#6469ff] dark:text-[#8a8eff] hover:underline flex items-center gap-1">
//               <span>View All</span>
//             </button>
//           </div>

//           {isLoading ? (
//             <div className="flex justify-center items-center h-64">
//               <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-[#6469ff]"></div>
//             </div>
//           ) : searchedResults.length > 0 ? (
//             <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
//               {/* This would be populated with actual search results */}
//             </div>
//           ) : (
//             <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
//               {/* Placeholder for empty state */}
//               <div className="col-span-full flex flex-col items-center justify-center h-64 bg-gray-100 dark:bg-gray-800 rounded-xl border border-dashed border-gray-300 dark:border-gray-700">
//                 <ImageIcon className="w-16 h-16 text-gray-400 mb-4" />
//                 <p className="text-gray-500 dark:text-gray-400 text-center max-w-md">
//                   No images found. Be the first to create something amazing!
//                 </p>
//                 <button className="mt-6 px-6 py-2 bg-[#6469ff] hover:bg-[#5258cc] text-white rounded-full flex items-center gap-2 transition-all">
//                   <Sparkles className="w-4 h-4" />
//                   <span>Create</span>
//                 </button>
//               </div>
//             </div>
//           )}
//         </div>

//         {/* Featured Section */}
//         <div className="mb-16">
//           <div className="flex justify-between items-center mb-6">
//             <h2 className="text-2xl font-bold text-gray-800 dark:text-gray-200">Featured Artists</h2>
//             <button className="text-[#6469ff] dark:text-[#8a8eff] hover:underline flex items-center gap-1">
//               <span>Explore</span>
//             </button>
//           </div>

//           <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
//             {[1, 2, 3].map((item) => (
//               <div key={item} className="bg-white dark:bg-gray-800 rounded-xl shadow-sm hover:shadow-md transition-shadow p-6 border border-gray-100 dark:border-gray-700">
//                 <div className="flex items-center gap-4 mb-4">
//                   <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center text-white font-bold">
//                     {item}
//                   </div>
//                   <div>
//                     <h3 className="font-medium text-gray-900 dark:text-white">Artist Name</h3>
//                     <p className="text-sm text-gray-500 dark:text-gray-400">@username</p>
//                   </div>
//                 </div>
//                 <p className="text-gray-600 dark:text-gray-300 mb-4">
//                   Creating stunning AI-generated landscapes and abstract art.
//                 </p>
//                 <button className="text-sm text-[#6469ff] dark:text-[#8a8eff] hover:underline">
//                   View Profile
//                 </button>
//               </div>
//             ))}
//           </div>
//         </div>
//       </main>

//       <PVFooter />
//     </div>
//   );
// };

// export default Home;

import React, { useEffect, useState } from "react";
import { Button } from "./ui";

import { ArrowRight, Sparkles, Zap, Image } from "lucide-react";

const Hero = () => {
  const [currentText, setCurrentText] = useState("");
  const [currentIndex, setCurrentIndex] = useState(0);

  const [isDeleting, setIsDeleting] = useState(false);

  const prompts = [
    "A majestic dragon soaring through clouds",
    "A futuristic city with neon lights",
    "A serene mountain landscape at sunset",
    "An abstract art piece with vibrant colors",
  ];

  useEffect(() => {
    const timeout = setTimeout(
      () => {
        const current = prompts[currentIndex];

        if (isDeleting) {
          setCurrentText(current.substring(0, currentText.length - 1));
          if (currentText === "") {
            setIsDeleting(false);
            setCurrentIndex((prevIndex) => (prevIndex + 1) % prompts.length);
          }
        } else {
          setCurrentText(current.substring(0, currentText.length + 1));
          if (currentText === current) {
            setTimeout(() => setIsDeleting(true), 2000);
          }
        }
      },
      isDeleting ? 50 : 100
    );

    return () => clearTimeout(timeout);
  }, [currentText, currentIndex, isDeleting, prompts]);

  const floatingElements = [
    { icon: Sparkles, delay: "0s", duration: "3s" },
    { icon: Zap, delay: "1s", duration: "4s" },
    { icon: Image, delay: "2s", duration: "3.5s" },
  ];

  return (
    <section className="min-h-screen pt-20 relative overflow-hidden">
      {/* Gradient Background */}
      <div className="absolute inset-0 bg-gradient-to-br from-[#D98A8C] via-[#E1C567] to-[#DFB573] dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
        <div className="absolute inset-0 bg-white/90 dark:bg-gray-900/80"></div>
      </div>

      {/* Floating Elements */}
      {floatingElements.map((element, index) => (
        <div
          key={index}
          className="absolute animate-bounce opacity-20 dark:opacity-10"
          style={{
            top: `${20 + index * 30}%`,
            right: `${10 + index * 15}%`,
            animationDelay: element.delay,
            animationDuration: element.duration,
          }}
        >
          <element.icon className="w-8 h-8 text-[#008055]" />
        </div>
      ))}

      <div className="container mx-auto px-6 py-16 relative z-10">
        <div className="max-w-4xl mx-auto text-center">
          {/* Main Headline */}
          <h1
            className="text-5xl md:text-6xl lg:text-7xl font-medium text-gray-900 dark:text-white mb-8 leading-tight"
            style={{
              fontFamily: "Balto Medium, Inter, sans-serif",
              letterSpacing: "-0.02em",
            }}
          >
            Transform Your Ideas Into
            <span className="block bg-gradient-to-r from-[#008055] to-[#0A6647] bg-clip-text text-transparent">
              Stunning AI Art
            </span>
          </h1>

          {/* Subtitle */}
          <p
            className="text-xl md:text-2xl text-gray-600 dark:text-gray-300 mb-12 max-w-3xl mx-auto leading-relaxed"
            style={{ fontFamily: "Balto Book, Inter, sans-serif" }}
          >
            Experience the future of creativity with our advanced AI image
            generation. Turn your wildest imagination into breathtaking visuals
            in seconds.
          </p>

          {/* Typing Animation */}
          <div className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-lg rounded-full px-8 py-4 mb-12 border border-gray-200/20 dark:border-gray-700/20 max-w-2xl mx-auto">
            <div className="flex items-center space-x-3">
              <div className="w-2 h-2 bg-[#008055] rounded-full animate-pulse"></div>
              <span
                className="text-gray-600 dark:text-gray-300 text-lg"
                style={{ fontFamily: "Balto Book, Inter, sans-serif" }}
              >
                "{currentText}"<span className="animate-blink">|</span>
              </span>
            </div>
          </div>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Button
              className="bg-[#008055] hover:bg-[#0A6647] active:bg-[#124E3B] text-white px-8 py-4 rounded-full text-lg transition-all duration-200 hover:scale-105 min-h-[56px]"
              style={{ fontFamily: "Balto Book, Inter, sans-serif" }}
            >
              Start Creating
              <ArrowRight className="w-5 h-5 ml-2" />
            </Button>

            <Button
              variant="outline"
              className="border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:border-[#008055] hover:text-[#008055] px-8 py-4 rounded-lg text-lg transition-all duration-200 inline-flex items-center justify-center"
              style={{ fontFamily: "Balto Book, Inter, sans-serif" }}
            >
              View Gallery
            </Button>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-3 gap-8 mt-16 pt-16 border-t border-gray-200/30 dark:border-gray-700/30">
            {[
              { number: "500K+", label: "Images Generated" },
              { number: "50K+", label: "Happy Users" },
              { number: "99.9%", label: "Uptime" },
            ].map((stat, index) => (
              <div key={index} className="text-center">
                <div
                  className="text-3xl md:text-4xl font-medium text-gray-900 dark:text-white mb-2"
                  style={{ fontFamily: "Balto Medium, Inter, sans-serif" }}
                >
                  {stat.number}
                </div>
                <div
                  className="text-gray-600 dark:text-gray-400"
                  style={{ fontFamily: "Balto Book, Inter, sans-serif" }}
                >
                  {stat.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
